# Generated by Django 4.2.17 on 2024-12-26 12:59

import custom_timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('source', models.CharField(choices=[('terms', '利用規約ページ'), ('signup', 'サインアップページ'), ('login', 'ログインページ'), ('other', 'その他')], default='other', max_length=20, verbose_name='問い合わせ元')),
                ('created_at', models.DateTimeField(default=custom_timezone.CustomTimezone.custom_now, verbose_name='送信日時')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('in_progress', '対応中'), ('completed', '対応済み')], default='pending', max_length=20, verbose_name='対応状況')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_contacts', to=settings.AUTH_USER_MODEL, verbose_name='対応者')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
