# Generated by Django 4.2.17 on 2024-12-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='対応日時'),
        ),
        migrations.AddField(
            model_name='contact',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_contacts', to=settings.AUTH_USER_MODEL, verbose_name='対応者'),
        ),
        migrations.AddField(
            model_name='contact',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name='対応内容'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', '未対応'), ('resolved', '対応済み')], default='pending', max_length=20, verbose_name='対応状況'),
        ),
    ]
