# Generated by Django 4.2.16 on 2024-11-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_maturi', '0004_remove_status_from_prediction'),
    ]

    operations = [
    ]
