# Generated by Django 4.2.17 on 2024-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_color',
            field=models.CharField(blank=True, default='', help_text='コメント表示用の色（#RRGGBB形式）', max_length=7),
        ),
    ]
