# Generated by Django 4.2.25 on 2025-10-12 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_comment_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_title_recruitment', models.BooleanField(default=True, help_text='月初（1日）に送信される同タイトル募集通知', verbose_name='同タイトル募集通知')),
                ('same_title_proposal', models.BooleanField(default=True, help_text='タイトル提案時に送信される通知', verbose_name='同タイトル提案通知')),
                ('same_title_decision', models.BooleanField(default=True, help_text='月の最初の投稿時に送信される通知', verbose_name='同タイトル決定通知')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メール通知設定',
                'verbose_name_plural': 'メール通知設定',
            },
        ),
    ]
