# Generated by Django 4.2.16 on 2024-11-17 08:59

import custom_timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game_same_title.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('proposed_at', models.DateTimeField(default=custom_timezone.CustomTimezone.custom_now, verbose_name='提案日時')),
                ('proposal_month', models.DateField(default=game_same_title.models.current_month, verbose_name='提案月')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提案者')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySameTitleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('month', models.CharField(max_length=7, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='関連小説')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_titles', to=settings.AUTH_USER_MODEL, verbose_name='提案者')),
            ],
        ),
        migrations.CreateModel(
            name='SameTitleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='エントリー月')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='エントリー日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
