# Generated by Django 4.2.11 on 2025-10-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_same_title', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SameTitleEntry',
        ),
    ]
