# Generated by Django 4.2.11 on 2025-10-13 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_same_title', '0002_remove_sametitleentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleproposal',
            name='proposed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提案日時'),
        ),
    ]
