# Generated by Django 4.2.25 on 2025-10-17 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_novel_unique_first_post_per_month'),
        ('game_same_title', '0003_alter_titleproposal_proposed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('same_title_decision', '同タイトル決定通知（一番槍）'), ('same_title_follower', '同タイトル追随通知（2番目以降）'), ('same_title_recruitment', '同タイトル募集通知（月初）')], max_length=50, verbose_name='通知タイプ')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='順位（追随通知用）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='予約日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('is_sent', models.BooleanField(default=False, verbose_name='送信済み')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='関連小説')),
            ],
            options={
                'verbose_name': 'メール通知予約',
                'verbose_name_plural': 'メール通知予約',
                'ordering': ['-created_at'],
            },
        ),
    ]
