# Generated by Django 4.2.25 on 2025-10-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_same_title', '0004_pendingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingnotification',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_same_title.titleproposal', verbose_name='関連タイトル提案'),
        ),
        migrations.AlterField(
            model_name='pendingnotification',
            name='notification_type',
            field=models.CharField(choices=[('提案', 'タイトル提案通知'), ('決定', '同タイトル決定通知（一番槍）'), ('追随', '同タイトル追随通知（2番目以降）'), ('same_title_recruitment', '同タイトル募集通知（月初）')], max_length=50, verbose_name='通知タイプ'),
        ),
    ]
