# Generated by Django 4.2.11 on 2025-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_same_title', '0005_pendingnotification_proposal_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pendingnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', '追随')), fields=('notification_type', 'novel', 'rank'), name='unique_follower_notification'),
        ),
        migrations.AddConstraint(
            model_name='pendingnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', '決定')), fields=('notification_type', 'novel'), name='unique_decision_notification'),
        ),
        migrations.AddConstraint(
            model_name='pendingnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', '提案')), fields=('notification_type', 'proposal'), name='unique_proposal_notification'),
        ),
    ]
