# Generated by Django 4.2.26 on 2025-11-11 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_same_title', '0006_pendingnotification_unique_follower_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='アクセスパス')),
                ('method', models.CharField(max_length=10, verbose_name='HTTPメソッド')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='アクセス日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アクセスログ',
                'verbose_name_plural': 'アクセスログ',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['-accessed_at'], name='game_same_t_accesse_e16ea9_idx'), models.Index(fields=['user', '-accessed_at'], name='game_same_t_user_id_2a40f8_idx'), models.Index(fields=['path', '-accessed_at'], name='game_same_t_path_4253f6_idx')],
            },
        ),
    ]
