# Generated by Django 4.2.17 on 2024-12-24 01:11

import custom_timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_maturi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('initial', models.CharField(blank=True, max_length=1, null=True)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=custom_timezone.CustomTimezone.custom_now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', '作成中'), ('scheduled', '予約公開'), ('published', '公開')], default='draft', max_length=10)),
                ('genre', models.CharField(choices=[('レジェンド小説', 'レジェンド小説'), ('初めましての挨拶', '初めましての挨拶'), ('ジョーク', 'ジョーク'), ('シリーズ', 'シリーズ'), ('サスペンス', 'サスペンス'), ('ファンタジー', 'ファンタジー'), ('同タイトル', '同タイトル'), ('恋愛', '恋愛'), ('日常', '日常'), ('祭り', '祭り'), ('雑談', '雑談'), ('ミステリー', 'ミステリー'), ('ノンフィクション', 'ノンフィクション'), ('ホラー', 'ホラー'), ('時代', '時代'), ('未分類', '未分類'), ('バトル', 'バトル'), ('大会', '大会'), ('コメディ', 'コメディ'), ('オフ会', 'オフ会'), ('歴史', '歴史'), ('私小説', '私小説'), ('官能', '官能'), ('三題噺', '三題噺'), ('旧祭���', '旧祭り'), ('旧同タイトル', '旧同タイトル')], default='未分類', max_length=100)),
                ('word_count', models.IntegerField(default=0, editable=False)),
                ('is_same_title_game', models.BooleanField(default=False)),
                ('same_title_event_month', models.CharField(blank=True, max_length=7, null=True)),
                ('afterword', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_novels', through='novels.Like', to=settings.AUTH_USER_MODEL)),
                ('original_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_novels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_maturi_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('maturi_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='game_maturi.maturigame')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novels.novel')),
                ('original_commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
