# Generated by Django 4.2.16 on 2024-11-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('レジェンド小説', 'レジェンド小説'), ('初めましての挨拶', '初めましての挨拶'), ('ジョーク', 'ジョーク'), ('シリーズ', 'シリーズ'), ('サスペンス', 'サスペンス'), ('ファンタジー', 'ファンタジー'), ('同タイトル', '同タイトル'), ('恋愛', '恋愛'), ('日常', '日常'), ('祭り', '祭り'), ('雑談', '雑談'), ('ミステリー', 'ミステリー'), ('ノンフィクション', 'ノンフィクション'), ('ホラー', 'ホラー'), ('時代', '時代'), ('未分類', '未分類'), ('バトル', 'バトル'), ('大会', '大会'), ('コメディ', 'コメディ'), ('オフ会', 'オフ会'), ('歴史', '歴史'), ('私小説', '私小説'), ('官能', '官能'), ('三題噺', '三題噺'), ('旧祭り', '旧祭り'), ('旧同タイトル', '旧同タイトル')], default='未分類', max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('draft', '作成中'), ('scheduled', '予約公開'), ('published', '公開')], default='draft', max_length=10),
        ),
    ]
