# Generated by Django 4.2.11 on 2025-10-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_novel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'novel'), name='unique_like_per_user'),
        ),
    ]
