# Generated by Django 4.2.11 on 2025-10-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_novel_published_date_like_unique_like_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='event',
            field=models.CharField(blank=True, choices=[('同タイトル', '同タイトル'), ('祭り', '祭り')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('恋愛', '恋愛'), ('SF', 'SF'), ('ミステリー', 'ミステリー'), ('ホラー', 'ホラー'), ('ファンタジー', 'ファンタジー'), ('その他', 'その他')], default='その他', max_length=100),
        ),
    ]
