# Generated by Django 4.2.25 on 2025-10-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_novel_event_alter_novel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='first_post_acquired_at',
            field=models.DateTimeField(blank=True, help_text='一番槍フラグが付与された日時', null=True, verbose_name='一番槍取得日時'),
        ),
        migrations.AddField(
            model_name='novel',
            name='is_first_post',
            field=models.BooleanField(default=False, help_text='同タイトル・同月で最初に投稿したか', verbose_name='一番槍'),
        ),
    ]
