# Generated by Django 4.2.11 on 2025-10-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_alter_novel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(choices=[('レジェンド小説', 'レジェンド小説'), ('初めましての挨拶', '初めましての挨拶'), ('ジョーク', 'ジョーク'), ('シリーズ', 'シリーズ'), ('サスペンス', 'サスペンス'), ('ファンタジー', 'ファンタジー'), ('恋愛', '恋愛'), ('日常', '日常'), ('雑談', '雑談'), ('ミステリー', 'ミステリー'), ('ノンフィクション', 'ノンフィクション'), ('ホラー', 'ホラー'), ('時代', '時代'), ('未分類', '未分類'), ('バトル', 'バトル'), ('大会', '大会'), ('コメディ', 'コメディ'), ('オフ会', 'オフ会'), ('歴史', '歴史'), ('私小説', '私小説'), ('官能', '官能'), ('三題噺', '三題噺')], max_length=100),
        ),
    ]
