# Generated by Django 4.2.11 on 2025-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_alter_novel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_same_title_failure',
            field=models.BooleanField(default=False, help_text='一番槍確定後、別タイトルで投稿した作品', verbose_name='同タイトル崩れ'),
        ),
    ]
