# Generated by Django 4.2.11 on 2025-10-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_novel_is_same_title_failure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='novel',
            constraint=models.UniqueConstraint(condition=models.Q(('event', '同タイトル'), ('is_first_post', True), ('status', 'published')), fields=('title', 'same_title_event_month'), name='unique_first_post_per_month'),
        ),
    ]
