# Generated by Django 4.2.17 on 2024-12-24 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('status', models.CharField(choices=[('pending', '保留中'), ('correct', '正解'), ('incorrect', '不正解')], default='pending', max_length=20, verbose_name='状態')),
            ],
            options={
                'verbose_name': '祭り予想',
                'verbose_name_plural': '祭り予想一覧',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='語句')),
            ],
        ),
        migrations.CreateModel(
            name='MaturiGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('prediction_start_date', models.DateField(verbose_name='作者予想の開始日')),
                ('prediction_end_date', models.DateField(verbose_name='作者予想の終了日')),
                ('entry_start_date', models.DateField(blank=True, null=True)),
                ('entry_end_date', models.DateField(blank=True, null=True)),
                ('maturi_start_date', models.DateField(blank=True, null=True, verbose_name='祭り開始日')),
                ('maturi_end_date', models.DateField(blank=True, null=True, verbose_name='祭り終了日')),
                ('year', models.CharField(editable=False, max_length=100, verbose_name='開催年度')),
                ('novel_publish_start_date', models.DateTimeField(verbose_name='小説公開開始日')),
                ('is_author_revealed', models.BooleanField(default=False, help_text='作者が公開済みの場合はTrue', verbose_name='作者公開済み')),
                ('dummy_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dummy_maturi_games', to=settings.AUTH_USER_MODEL)),
                ('entrants', models.ManyToManyField(blank=True, related_name='entered_games', to=settings.AUTH_USER_MODEL, verbose_name='エントリー参加者')),
            ],
        ),
    ]
