# Generated by Django 4.2.17 on 2024-12-24 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_maturi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturigame',
            name='maturi_novels',
            field=models.ManyToManyField(blank=True, limit_choices_to={'genre': '祭り'}, related_name='maturi_games', to='novels.novel', verbose_name='祭りの小説'),
        ),
        migrations.AddField(
            model_name='maturigame',
            name='phrases',
            field=models.ManyToManyField(blank=True, to='game_maturi.phrase', verbose_name='語句'),
        ),
        migrations.AddField(
            model_name='gameprediction',
            name='maturi_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='game_maturi.maturigame', verbose_name='祭りゲーム'),
        ),
        migrations.AddField(
            model_name='gameprediction',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='novels.novel', verbose_name='小説'),
        ),
        migrations.AddField(
            model_name='gameprediction',
            name='predicted_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_predictions', to=settings.AUTH_USER_MODEL, verbose_name='予想された作者'),
        ),
        migrations.AddField(
            model_name='gameprediction',
            name='predictor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_predictions', to=settings.AUTH_USER_MODEL, verbose_name='予想者'),
        ),
        migrations.AlterUniqueTogether(
            name='gameprediction',
            unique_together={('maturi_game', 'novel', 'predictor')},
        ),
    ]
