# Generated by Django 4.2.16 on 2024-11-24 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_maturi', '0002_alter_gameprediction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprediction',
            name='status',
            field=models.CharField(
                choices=[('pending', '保留中'), ('correct', '正解'), ('incorrect', '不正解')],
                default='pending',
                max_length=20,
                verbose_name='状態'
            ),
        ),
        migrations.AddField(
            model_name='maturigame',
            name='novel_publish_start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 5, 51, 3, 809778, tzinfo=datetime.timezone.utc), verbose_name='小説公開開始日'),
            preserve_default=False,
        ),
    ]
