# Generated by Django 4.2.16 on 2024-11-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_maturi', '0003_gameprediction_status_and_more'),
    ]

    operations = [
    ]
