# Generated by Django 4.2.16 on 2024-11-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_maturi', '0004_remove_maturi_novel'),
        ('game_maturi', '0004_remove_maturi_novel_fix'),
    ]

    operations = [
    ]
