# Generated by Django 4.2.16 on 2024-11-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_maturi', '0005_merge_20241125_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprediction',
            name='status',
            field=models.CharField(
                choices=[('pending', '保留中'), ('correct', '正解'), ('incorrect', '不正解')],
                default='pending',
                max_length=20,
                verbose_name='状態'
            ),
        ),
    ]
