# Generated by Django 4.2.26 on 2025-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_add_opening_notification_sent'),
        ('game_maturi', '0008_alter_maturigame_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturigame',
            name='opening_notification_sent',
            field=models.BooleanField(default=False, help_text='祭り開幕通知を送信済みの場合はTrue', verbose_name='開幕通知送信済み'),
        ),
        migrations.AlterField(
            model_name='maturigame',
            name='maturi_novels',
            field=models.ManyToManyField(blank=True, related_name='maturi_games', to='novels.novel', verbose_name='祭りの小説'),
        ),
    ]
